<?php

namespace justinback\steam;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-02-24 at 21:16:35.
 */
class achievementsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var achievements
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new achievements;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers justinback\steam\achievements::GetPlayerAchievements
     * @todo   Implement testGetPlayerAchievements().
     */
    public function testGetPlayerAchievements() {
        
    }

    /**
     * @covers justinback\steam\achievements::GetPlayerAchievementsLocked
     * @todo   Implement testGetPlayerAchievementsLocked().
     */
    public function testGetPlayerAchievementsLocked() {
        
    }

    /**
     * @covers justinback\steam\achievements::GetAchievementDetails
     * @todo   Implement testGetAchievementDetails().
     */
    public function testGetAchievementDetails() {
        
    }

    /**
     * @covers justinback\steam\achievements::HasPlayerUnlockedAchievement
     * @todo   Implement testHasPlayerUnlockedAchievement().
     */
    public function testHasPlayerUnlockedAchievement() {
        
    }

    /**
     * @covers justinback\steam\achievements::game
     * @todo   Implement testGame().
     */
    public function testGame() {
        
    }

}
