<?php

namespace justinback\steam;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-02-24 at 21:16:39.
 */
class groupTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var group
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new group;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers justinback\steam\group::GetGroupName
     * @todo   Implement testGetGroupName().
     */
    public function testGetGroupName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\group::GetGroupURL
     * @todo   Implement testGetGroupURL().
     */
    public function testGetGroupURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\group::GetGroupHeadline
     * @todo   Implement testGetGroupHeadline().
     */
    public function testGetGroupHeadline() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\group::GetGroupSummary
     * @todo   Implement testGetGroupSummary().
     */
    public function testGetGroupSummary() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\group::GetGroupID64
     * @todo   Implement testGetGroupID64().
     */
    public function testGetGroupID64() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\group::GetGroupAvatar
     * @todo   Implement testGetGroupAvatar().
     */
    public function testGetGroupAvatar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\group::GetGroupMembers
     * @todo   Implement testGetGroupMembers().
     */
    public function testGetGroupMembers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\group::GetGroupStats
     * @todo   Implement testGetGroupStats().
     */
    public function testGetGroupStats() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
