<?php

namespace justinback\steam;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-02-24 at 21:16:40.
 */
class leaderboardsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var leaderboards
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new leaderboards;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers justinback\steam\leaderboards::DeleteLeaderboard
     * @todo   Implement testDeleteLeaderboard().
     */
    public function testDeleteLeaderboard() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\leaderboards::FindOrCreateLeaderboard
     * @todo   Implement testFindOrCreateLeaderboard().
     */
    public function testFindOrCreateLeaderboard() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\leaderboards::ResetLeaderboard
     * @todo   Implement testResetLeaderboard().
     */
    public function testResetLeaderboard() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\leaderboards::SetLeaderboardScore
     * @todo   Implement testSetLeaderboardScore().
     */
    public function testSetLeaderboardScore() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\leaderboards::GetLeaderboardsForGame
     * @todo   Implement testGetLeaderboardsForGame().
     */
    public function testGetLeaderboardsForGame() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\leaderboards::GetLeaderboardEntries
     * @todo   Implement testGetLeaderboardEntries().
     */
    public function testGetLeaderboardEntries() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\leaderboards::game
     * @todo   Implement testGame().
     */
    public function testGame() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
