<?php

namespace justinback\steam;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-02-24 at 21:16:34.
 */
class playerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var player
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new player;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers justinback\steam\player::GetPersonaName
     * @todo   Implement testGetPersonaName().
     */
    public function testGetPersonaName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::GetPlayerBans
     * @todo   Implement testGetPlayerBans().
     */
    public function testGetPlayerBans() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::GetFriendList
     * @todo   Implement testGetFriendList().
     */
    public function testGetFriendList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::GetUserGroupList
     * @todo   Implement testGetUserGroupList().
     */
    public function testGetUserGroupList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::GetSteamIDs
     * @todo   Implement testGetSteamIDs().
     */
    public function testGetSteamIDs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::GetAvatar
     * @todo   Implement testGetAvatar().
     */
    public function testGetAvatar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::GetRealName
     * @todo   Implement testGetRealName().
     */
    public function testGetRealName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::ReportPlayerCheating
     * @todo   Implement testReportPlayerCheating().
     */
    public function testReportPlayerCheating() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::ReportAbuse
     * @todo   Implement testReportAbuse().
     */
    public function testReportAbuse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::RemovePlayerGameBan
     * @todo   Implement testRemovePlayerGameBan().
     */
    public function testRemovePlayerGameBan() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::EnumerateUserPublishedFiles
     * @todo   Implement testEnumerateUserPublishedFiles().
     */
    public function testEnumerateUserPublishedFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::achievements
     * @todo   Implement testAchievements().
     */
    public function testAchievements() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::inventory
     * @todo   Implement testInventory().
     */
    public function testInventory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\player::transactions
     * @todo   Implement testTransactions().
     */
    public function testTransactions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
