<?php

namespace justinback\steam;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-02-24 at 21:16:41.
 */
class transactionsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var transactions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new transactions;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers justinback\steam\transactions::AdjustAgreement
     * @todo   Implement testAdjustAgreement().
     */
    public function testAdjustAgreement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\transactions::CancelAgreement
     * @todo   Implement testCancelAgreement().
     */
    public function testCancelAgreement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\transactions::RefundTxn
     * @todo   Implement testRefundTxn().
     */
    public function testRefundTxn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\transactions::FinalizeTxn
     * @todo   Implement testFinalizeTxn().
     */
    public function testFinalizeTxn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\transactions::QueryTxn
     * @todo   Implement testQueryTxn().
     */
    public function testQueryTxn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\transactions::GetUserAgreementInfo
     * @todo   Implement testGetUserAgreementInfo().
     */
    public function testGetUserAgreementInfo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\transactions::InitTxn
     * @todo   Implement testInitTxn().
     */
    public function testInitTxn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\transactions::ProcessAgreement
     * @todo   Implement testProcessAgreement().
     */
    public function testProcessAgreement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\transactions::GetReport
     * @todo   Implement testGetReport().
     */
    public function testGetReport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
