<?php

namespace justinback\steam;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-02-24 at 21:16:39.
 */
class ugcTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ugc
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ugc;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers justinback\steam\ugc::UpdateBanStatus
     * @todo   Implement testUpdateBanStatus().
     */
    public function testUpdateBanStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\ugc::UpdateIncompatibleStatus
     * @todo   Implement testUpdateIncompatibleStatus().
     */
    public function testUpdateIncompatibleStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\ugc::UpdateTags
     * @todo   Implement testUpdateTags().
     */
    public function testUpdateTags() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\ugc::GetPublishedFileDetails
     * @todo   Implement testGetPublishedFileDetails().
     */
    public function testGetPublishedFileDetails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\ugc::SubscribePublishedFile
     * @todo   Implement testSubscribePublishedFile().
     */
    public function testSubscribePublishedFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\ugc::UnsubscribePublishedFile
     * @todo   Implement testUnsubscribePublishedFile().
     */
    public function testUnsubscribePublishedFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\ugc::QueryFiles
     * @todo   Implement testQueryFiles().
     */
    public function testQueryFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\ugc::player
     * @todo   Implement testPlayer().
     */
    public function testPlayer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
