<?php

namespace justinback\steam;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-03-23 at 22:23:06.
 */
class userauthTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var userauth
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new userauth;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers justinback\steam\userauth::AuthenticateUser
     * @todo   Implement testAuthenticateUser().
     */
    public function testAuthenticateUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\userauth::AuthenticateUserTicket
     * @todo   Implement testAuthenticateUserTicket().
     */
    public function testAuthenticateUserTicket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
