<?php

namespace justinback\steam;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-03-23 at 22:23:07.
 */
class utilsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var utils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new utils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers justinback\steam\utils::IsValidSteamID
     * @todo   Implement testIsValidSteamID().
     */
    public function testIsValidSteamID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers justinback\steam\utils::ConvertSteamIDs
     * @todo   Implement testConvertSteamIDs().
     */
    public function testConvertSteamIDs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
