language: php

php:

  # aliased to a recent 5.6.x version
  - 5.6
  
script: 
  - phpunit --bootstrap steam.php --coverage-text tests
  
  
# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
    
