<?php

namespace justinback\steam\exceptions;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-03-23 at 22:23:07.
 */
class SteamRequestParameterExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SteamRequestParameterException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SteamRequestParameterException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
